### ISSUE TITLE
Add ability to copy password to clipboard

### ISSUE THREAD

**Issue by samdrudd** [samdrudd/passman#4]
We have the button, just need to add the actual functionality

**Comment by vbmade2000** [comment]
I have implemented this functionality and submitted PR. Please have a look.

**Comment by samdrudd** [comment]
I implemented this in my most recent commit before I saw your PR so I am closing this issue. I did also review your PR if you want to take a look at my comments.

**Comment by vbmade2000** [comment]
Ah Ok. No probs.
